name: deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: pnpm install
      - name: Run migrations on prod
        run: pnpm migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
